### ISSUE TITLE
Problem with cmsplugin-filer-image in latest installer

### ISSUE THREAD

**Issue by maxkeogh** [divio/cmsplugin-filer#215]
Hi,

I set up a fresh install of DjangoCMS using this link as the guide: http://docs.django-cms.org/en/develop/introduction/install.html
I chose cms version 3.1, and django version 1.8. The install went fine and runserver brought up the standard page as expected. However, when I edited the page and added an image the plugin instance on the Structure page showed Image Empty.
![filer-image-error](https://cloud.githubusercontent.com/assets/8715120/12445439/2400e3cc-bf5c-11e5-9d84-80795b249fe5.png)

I have another cms instance where the images do work. I checked the versions of the installed components and they were slightly earlier versions. The versions that work are:
cmsplugin-filer==1.0.0
django-filer==1.0.2
Pillow==3.0.0

On the latest install that produces the error the versions are:
cmsplugin-filer==1.0.1
django-filer==1.0.6
Pillow==3.1.0

I downgraded these 3 components and I could then add images onto the page.
I thought I should let you know of this error on these versions.

I posted this issue on the djangocms-installer page and they suggested I raise the issue here.

Kind regards
max

**Comment by stefanfoulis** [comment]
@maxkeogh thanks for the report. I just re-tested with ``django-cms==3.1.x`` and ``Django==1.8.x``and was unable to reproduce the error.
It is very possible that the problem has since been fixed somewhere else. Maybe in django-filer ``1.1.1``.

I also tested with ``django-cms==3.2.x`` and ``Django==1.9.x`` without errors.

Feel free to re-open this issue if you are still experiencing the error.
