### ISSUE TITLE
Doesn't work with Django 1.9

### ISSUE THREAD

**Issue by farooqaaa** [divio/cmsplugin-filer#230]
When you run migrations in Django 1.9 it gives the message "there is no South database module". I don't have south in my INSTALLED_APPS. I tried uninstalling south but then it says that south is not found.

I think it's because of the migrations using south. I tried removing all the migrations and it worked fine.

**Comment by stefanfoulis** [comment]
@farooqaaa thanks for reporting. With which plugins are you experiencing this problem?

**Comment by farooqaaa** [comment]
All of them. I also tried individual plugins but it's still the same

**Comment by stefanfoulis** [comment]
Ah, sorry I forgot that we've not released the fix for this yet. It works out of the box on the develop branch, but there we're still waiting on a release of django-filer itself.

See the part about ``MIGRATION_MODULES`` in the 1.0.1 readme: https://github.com/divio/cmsplugin-filer/blob/1.0.1/README.rst
It describes how to use cmsplugin-filer with Django 1.7+

This will no longer be necessary with the next release.
